### ISSUE TITLE
Compile error in Debian11

### ISSUE THREAD

**Issue by RigCor7** [Kei18/lacam3#1]
Hello Keisuke,

I met one problem when I compiled the program in Debian11 as below:

`[build] /usr/bin/ld: lacam3/liblacam3.a(dist_table.cpp.o): in function DistTable::setup(Instance const*):`
`[build] /usr/include/c++/10/thread:149: undefined reference to pthread_create`
`[build] /usr/bin/ld: lacam3/liblacam3.a(planner.cpp.o): in function Planner::set_new_config(HNode*, LNode*, std::vector<Vertex*, std::allocator<Vertex*> >&)`:
`[build] /usr/include/c++/10/thread:149: undefined reference to pthread_create`

It also didn't work if adding the <pthread.h>  to the file and linking the pthread library in the CmakeLists.txt.

Could you help me check the error? Thanks a lot!

**Comment by Kei18** [comment]
Hi, I'm sorry but I don't have much clue other than header modifications as I don't have Debian env. At least this repo works with Ubuntu... Could you check if `std::future` works correctly with a toy example? 

Keisuke

**Comment by RigCor7** [comment]
Hi Keisuke,

Thanks for your reply. 

I try the toy example about `std::future`, and it must add the `-pthread` when compiling the program in debian11. Then, I added the pthread to target_link_libraries in lacam3 CMakeLists.txt and removed the test part, and it worked. Maybe there is something wrong with the test file?

Yuqi

**Comment by Kei18** [comment]
Hi Yuqi,

Glad to hear that the code works, when removing the test. I will investigate this later, so I will keep this GitHub issue open. Thanks for reporting!

**Comment by opan08** [comment]
> Hello Keisuke,
> 
> I met one problem when I compiled the program in Debian11 as below:
> 
> `[build] /usr/bin/ld: lacam3/liblacam3.a(dist_table.cpp.o): in function DistTable::setup(Instance const*):` `[build] /usr/include/c++/10/thread:149: undefined reference to pthread_create` `[build] /usr/bin/ld: lacam3/liblacam3.a(planner.cpp.o): in function Planner::set_new_config(HNode*, LNode*, std::vector<Vertex*, std::allocator<Vertex*> >&)`: `[build] /usr/include/c++/10/thread:149: undefined reference to pthread_create`
> 
> It also didn't work if adding the <pthread.h> to the file and linking the pthread library in the CmakeLists.txt.
> 
> Could you help me check the error? Thanks a lot!

@RigCor7 I have the same error in ubuntu 20.04.

Maybe you can add `target_link_libraries(${PROJECT_NAME} PUBLIC pthread)` in file `lacam3/CMakeLists.txt`

It works for me

**Comment by Kei18** [comment]
Thank you for reporting!

@opan08 / @RigCor7  Could you please test the following pull request? I have updated CmakeLists.txt. If this works, I would like to update the main branch.
https://github.com/Kei18/lacam3/pull/2

**Comment by opan08** [comment]
> Thank you for reporting!
> 
> @opan08 / @RigCor7 Could you please test the following pull request? I have updated CmakeLists.txt. If this works, I would like to update the main branch. #2

@Kei18 Yes, it works in ubuntu 20.04.

**Comment by Kei18** [comment]
Thanks for the confirmation!
